### ISSUE TITLE
Can toggle be active and grayed out?

### ISSUE THREAD

**Issue by e-t-l** [chenxiaolong/OEMUnlockOnBoot#4]
Is there any way to make the toggle set to active, but also grayed out, so that it's physically impossible for a user to toggle it off (without first uninstalling this magisk module)?

**Comment by chenxiaolong** [comment]
I wish there was a good way to do that, but unfortunately not. The only two situations where Android grays out the option are:

* OEM or carrier disallows bootloader unlocks (this state is stored in the bootloader itself)
* There's a (eg. corporate) device management app installed that's configured to disallow factory resets

An Xposed module could also gray out the option, but I don't really have any interest in making one.
